### ISSUE TITLE
In-browser version

### ISSUE THREAD

**Issue by ram-you** [tiagorg/marionette-vdom#6]
Hi,
What about a "in-browser" version (not server-mode node.js)  ?

**Comment by tiagorg** [comment]
That is a great suggestion, I've thought on it already. That would be a great goal for the next minor. version.

One idea is to use UMD approach to make it deliverable through both CommonJS and AMD. 

Do you have any suggestion?

**Comment by samccone** [comment]
yep UMD seems like the best approach here, @tiagorg I can help you set it up if you would like

**Comment by tiagorg** [comment]
hey @samccone - sure I would love to! :)

please let me know if you prefer pairing up, or doing on your own and sending a PR.

I will then create a branch for this new approach to be released on 0.2.0

**Comment by ram-you** [comment]
Hi @tiagorg and @samccone  - good news. Thank you for both.

**Comment by timtan** [comment]
good news, thanks so much!

**Comment by samccone** [comment]
I am getting to this, i promise!

**Comment by jimbriam** [comment]
Anxiously looking forward to trying this out.

**Comment by filipmares** [comment]
+1

**Comment by samccone** [comment]
gah I promise I will do this :) so many things in flight hahaha

**Comment by tiagorg** [comment]
Published version 0.1.2-b featuring the browser/AMD version on a dist/ folder

https://www.npmjs.com/package/marionette-vdom
