### ISSUE TITLE
Support for LayoutViews

### ISSUE THREAD

**Issue by jiaweihli** [tiagorg/marionette-vdom#9]
The only real view left!  What do we need to do to support this?  Any roadblocks I can help with?

**Comment by tiagorg** [comment]
Hey @jiaweihli - as far as I understand, ```LayoutView``` extends from ```ItemView``` which is being covered, and it also doesn't do any specific rendering on its own (instead, it manages ```Region```s and put them to render) so initially I thought there was not much else to be done for it. The code is here: https://github.com/marionettejs/backbone.marionette/blob/master/src/layout-view.js

Anyhow, I can't take my analysis for granted so if you see any potential for implementing VDOM please bring it up, and if you feel so, please be more than welcome to join us playing with it as well :)

**Comment by jeffijoe** [comment]
Support for layout views would ultimately make fine-grained UI updates on a per-attribute basis redundant - `change: 'render'` all the way. :P

**Comment by jiaweihli** [comment]
As @jeffijoe mentioned, the issue is that sometimes `LayoutViews` are completely re-rendered - this destroys its child `ItemViews`.

**Comment by tiagorg** [comment]
I see. so yes it would be nice to add ```LayoutViews``` specific support that won't destroy its ```ItemViews```.

@jiaweihli I just saw your post on Gitter, is your ```CompositeView``` suffering from the same thing?

Two things that I wanted to understand are: 
a) Is your ```LayoutView``` / ```CompositeView``` composed only by VDOM ```ItemViews```? 
b) If not, would you please try that and tell me if it would still re-create everything?

**Comment by jiaweihli** [comment]
**A:**
Sometimes, sometimes not.

**B:**
Yes, it would still re-create everything, since I'm binding `change: 'render'` in `modelEvents`.

I've run into each of these cases:
  - I need to re-render a portion of the view's template (it depends on a model attribute), which forces `onRender` and re-rendering my children.
  - I want to re-render a specific `LayoutView` child.
  - I need to re-render a `CompositeView` child because I need to re-evaluate its `attachHtml` function.

**Comment by tiagorg** [comment]
Gotcha. Thanks! I will have a look this Sunday

**Comment by tiagorg** [comment]
I have just released v0.2.1 with Marionette 3 support, which replaces `LayoutView` and `ItemView` with just a `View`. Hence, I'm closing this issue since everything will be covered already by `View`.

**Comment by trystian1** [comment]
In our application we support it like:

**Comment by tiagorg** [comment]
Cool. Thanks @trystian1 - your solution would be the case for Marionette 2.
